- name: Install DNS server
  hosts: dns
  tasks:
    - name: Install bind9
      apt:
        name: bind9
        state: latest

    - name: Copy DNS database
      copy: src=db.competitor dest=/etc/bind/db.competitor
      when: "{{inventory_hostname=='srv1'}}"

    - name: Copy DNS master config
      copy: src=named.conf.local dest=/etc/bind/named.conf.local
      when: "{{inventory_hostname=='srv1'}}"

    - name: Copy DNS slave config
      copy: src=named.conf.slave dest=/etc/bind/named.conf.local
      when: "{{inventory_hostname=='srv2'}}"

    - name: Restart the bind9 service
      service:
        name: bind9
        state: restarted
